sudo: required
language: python
services:
- docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here
  - chmod +x deploy.sh

script:
  - echo "no tests!" # put your normal testing scripts here


after_success:
- docker --version
- docker build -t docker-wordcount .
- ./deploy.sh
env:
  global:
  - secure: 
  - secure: 
  - secure: 
  
